### ISSUE TITLE
Cannot start the xicam successfully on Win11

### ISSUE THREAD

**Issue by axingxing** [Xi-CAM/Xi-cam#102]
My environment is Win 11 and I'm using the py3.8 in anaconda
I followed the document and then downgraded intake=0.5.5, databroker=1.0.2, pyYAML=5.4.1 and installed tiled, httpx, doct
but when I "python run_xicam.py"，it reports the error

```
Fri Dec 22 15:53:36 2023 - restore - ERROR - MainThread >
 The following error was handled safely by Xi-cam. It is displayed here for debugging.
Fri Dec 22 15:53:36 2023 - restore - ERROR - MainThread >
 Traceback (most recent call last):
   File "D:\anaconda\envs\xicam\lib\site-packages\xicam\plugins\settingsplugin.py", line 49, in restore
    self.fromState(pickle.loads(state))
 TypeError: a bytes-like object is required, not 'NoneType'

**Fri Dec 22 15:53:36 2023 - restore - WARNING - MainThread > Could not restore settings for <bound method Parameter.name of <AppearanceSettingsPlugin 'Appearance' at 0x28b8e350ee0>> plugin; re-initializing settings...
Fri Dec 22 15:53:37 2023 - logError - ERROR - MainThread >
 The following error was handled safely by Xi-cam. It is displayed here for debugging.
Fri Dec 22 15:53:37 2023 - logError - ERROR - MainThread >
 Traceback (most recent call last):
   File "D:\anaconda\envs\xicam\Lib\site-packages\xicam\run_xicam.py", line 124, in <module>
    return_code = main()
   File "D:\anaconda\envs\xicam\Lib\site-packages\xicam\run_xicam.py", line 97, in main
    return _main(args)
   File "D:\anaconda\envs\xicam\Lib\site-packages\xicam\run_xicam.py", line 83, in _main
    mainwindow = XicamMainWindow()
   File "D:\anaconda\envs\xicam\lib\site-packages\xicam\gui\windows\mainwindow.py", line 98, in __init__
    file.addAction("Se&ttings", self.showSettings, shortcut=QKeySequence(Qt.CTRL + Qt.ALT + Qt.Key_S))
 TypeError: add_action() got an unexpected keyword argument 'shortcut'**
```

**Desktop (please complete the following information):**
 - OS: Win 11
 - Xi-CAM Version:2.4.6

**Comment by ronpandolfi** [comment]
Please share the following to help me investigate your issue:

1. A `pip list` or `conda list` of your environment
2. What source are you installing Xi-cam from (pypi, github source, conda-forge)?
3. What directions are you following?
4. Do you have an external requirement to use a conda environment, or could you use a standard python 'venv'?

Also, please reach out to me by email. I'd like to know a bit about how/where you plan to use Xi-cam so I can better support you even after this issue is resolved.

**Comment by ronpandolfi** [comment]
This issue appears to result from recent changes in the `qtpy` package. This is a dependency used to abstract versions of Qt bindings.

For now, you can rollback to an earlier version of qtpy that still works as follows:
```
pip install "qtpy<2.4"
```
I will also be working on a solution to address this during standard installation.

Edit:
I've opened an issue on qtpy: https://github.com/spyder-ide/qtpy/issues/472
I've also pushed a fix that pins the qtpy version to <2.4 (7f756aee9a0513c44d85459144bef127b0e35707). I'll try to get this published to PyPI soon.

**Comment by axingxing** [comment]
> This issue appears to result from recent changes in the `qtpy` package. This is a dependency used to abstract versions of Qt bindings.
> 
> For now, you can rollback to an earlier version of qtpy that still works as follows:
> 
> ```
> pip install "qtpy<2.4"
> ```
> 
> I will also be working on a solution to address this during standard installation.
> 
> Edit: I've opened an issue on qtpy: [spyder-ide/qtpy#472](https://github.com/spyder-ide/qtpy/issues/472) I've also pushed a fix that pins the qtpy version to <2.4 ([7f756ae](https://github.com/Xi-CAM/Xi-cam/commit/7f756aee9a0513c44d85459144bef127b0e35707)). I'll try to get this published to PyPI soon.

Thank you for your reply. I downgraded qtpy=2.3 and qtconsole=5.3.
And then I started the xicam. 
Here is my pip list. Hope it helps.

`Package                   Version
------------------------- ------------
anyio                     4.2.0
appdirs                   1.4.4
asciitree                 0.3.3
astropy                   5.2.2
asttokens                 2.4.1
attrs                     23.1.0
backcall                  0.2.0
backports.zoneinfo        0.2.1
bluesky-live              0.0.8
bluesky-widgets           0.0.15
boltons                   23.1.1
cachetools                5.3.2
camsaxs                   1.0.3
certifi                   2023.11.17
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
colorama                  0.4.6
comm                      0.2.0
contourpy                 1.1.1
cycler                    0.12.1
dask                      2023.5.0
databroker                1.0.2
debugpy                   1.8.0
decorator                 5.1.1
distlib                   0.3.8
distributed               2023.5.0
dnspython                 2.4.2
doct                      1.1.0
entrypoints               0.4
event-model               1.19.9
exceptiongroup            1.2.0
executing                 2.0.1
fabio                     2023.10.0
fasteners                 0.19
filelock                  3.13.1
fonttools                 4.47.0
fsspec                    2023.12.2
h11                       0.14.0
h5py                      3.10.0
hdf5plugin                4.3.0
httpcore                  1.0.2
httpx                     0.26.0
humanize                  4.9.0
idna                      3.6
imageio                   2.33.1
importlib-metadata        7.0.0
importlib-resources       6.1.1
intake                    0.5.5
ipykernel                 6.27.1
ipython                   8.12.3
ipython-genutils          0.2.0
jedi                      0.19.1
Jinja2                    3.1.2
jsonschema                4.20.0
jsonschema-specifications 2023.11.2
jupyter_client            8.6.0
jupyter_core              5.5.1
kiwisolver                1.4.5
lazy_loader               0.3
locket                    1.0.0
lxml                      4.9.4
MarkupSafe                2.1.3
matplotlib                3.7.4
matplotlib-inline         0.1.6
mongoquery                1.4.2
msgpack                   1.0.7
msgpack-numpy             0.4.8
nest-asyncio              1.5.8
networkx                  3.1
numcodecs                 0.12.1
numexpr                   2.8.6
numpy                     1.24.4
packaging                 23.2
pandas                    2.0.3
parso                     0.8.3
partd                     1.4.1
pathlib                   1.0.1
pickleshare               0.7.5
Pillow                    10.1.0
PIMS                      0.6.1
pip                       23.3.1
pkgutil_resolve_name      1.3.10
platformdirs              4.1.0
ply                       3.11
prettytable               3.9.0
prompt-toolkit            3.0.43
psutil                    5.9.7
pure-eval                 0.2.2
pyerfa                    2.0.0.3
pyfai                     2023.9.0
Pygments                  2.17.2
pymongo                   4.6.1
pyparsing                 3.1.1
PyQt5                     5.15.0
PyQt5-sip                 12.13.0
pyqtgraph                 0.11.0
python-dateutil           2.8.2
pytz                      2023.3.post1
PyWavelets                1.4.1
pywin32                   306
PyYAML                    5.4.1
pyzmq                     25.1.2
QDarkStyle                3.2.3
qtconsole                 5.3.0
qtmodern                  0.2.0
QtPy                      2.3.0
referencing               0.32.0
requests                  2.31.0
rpds-py                   0.15.2
sasmodels                 1.0.7
scikit-image              0.21.0
scipy                     1.10.1
setuptools                68.2.2
silx                      1.1.2
sip                       6.7.12
six                       1.16.0
slicerator                1.1.0
sniffio                   1.3.0
sortedcontainers          2.4.0
stack-data                0.6.3
suitcase-mongo            0.4.0
suitcase-msgpack          0.3.0
suitcase-utils            0.5.3
tblib                     3.0.0
tifffile                  2023.7.10
tiled                     0.1.0a110
tomli                     2.0.1
toolz                     0.12.0
tornado                   6.4
traitlets                 5.14.0
typing_extensions         4.9.0
tzdata                    2023.3
tzlocal                   5.2
urllib3                   2.1.0
virtualenv                20.25.0
wcwidth                   0.2.12
wheel                     0.41.2
xarray                    2023.1.0
xicam                     2.3.0
zarr                      2.16.1
zict                      3.0.0
zipp                      3.17.0`
