### ISSUE TITLE
Startup crash due to intake configuration issue

### ISSUE THREAD

**Issue by dylanmcreynolds** [Xi-CAM/Xi-cam#3]
If you configure yaml files so that the source name appears twice, intake throws an error (shown below). This crashes Xi-Cam

I configured this by copying my souces yml file into a second exact same copy in ~/.local/share/intake.

The problem appears to be here: https://github.com/Xi-CAM/Xi-cam/blob/61cdf6a61c2f7549cf186dcee7b523ed78a1ce50/xicam/gui/windows/mainwindow.py#L3

The import statement is not wrapped in exception handling.

 env /home/dylan/work/xicam/env/bin/python /home/dylan/.vscode/extensions/ms-python.python-2020.5.80290/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher 40125 -- /home/dylan/work/xicam/Xi-cam/xicam/run_xicam.py 
(env) ~/work/xicam$  env /home/dylan/work/xicam/env/bin/python /home/dylan/.vscode/extensions/ms-python.python-2020.5.80290/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher 40125 -- /home/dylan/work/xicam/Xi-cam/xicam/run_xicam.py 
args: ['/home/dylan/work/xicam/Xi-cam/xicam/run_xicam.py']
path: ['/home/dylan/work/xicam/Xi-cam/xicam', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/dylan/work/xicam/env/lib/python3.8/site-packages', '/home/dylan/work/xicam/Xi-cam', '/home/dylan/work/xicam/Xi-cam.CatalogViewer', '/home/dylan/work/xicam/intake', '/home/dylan/work/xicam/databroker']
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/dylan/work/xicam/Xi-cam/xicam/core/msg/__init__.py", line 290, in logError
    kwargs["loggername"] = sys._getframe().f_back.f_code.co_name
AttributeError: 'NoneType' object has no attribute 'f_code'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dylan/.vscode/extensions/ms-python.python-2020.5.80290/pythonFiles/lib/python/debugpy/no_wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/dylan/.vscode/extensions/ms-python.python-2020.5.80290/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/dylan/.vscode/extensions/ms-python.python-2020.5.80290/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dylan/work/xicam/Xi-cam/xicam/run_xicam.py", line 81, in <module>
    return_code = main()
  File "/home/dylan/work/xicam/Xi-cam/xicam/run_xicam.py", line 77, in main
    return _main(args)
  File "/home/dylan/work/xicam/Xi-cam/xicam/run_xicam.py", line 55, in _main
    from xicam.gui.windows.mainwindow import XicamMainWindow
  File "/home/dylan/work/xicam/Xi-cam/xicam/gui/windows/mainwindow.py", line 3, in <module>
    from intake.catalog import Catalog
  File "/home/dylan/work/xicam/intake/intake/__init__.py", line 31, in <module>
    for name, driver in autodiscover().items():
  File "/home/dylan/work/xicam/intake/intake/source/discovery.py", line 145, in autodiscover
    drivers[entrypoint.name] = _load_entrypoint(entrypoint)
  File "/home/dylan/work/xicam/intake/intake/source/discovery.py", line 250, in _load_entrypoint
    return entrypoint.load()
  File "/home/dylan/work/xicam/env/lib/python3.8/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/dylan/work/xicam/databroker/databroker/__init__.py", line 20, in <module>
    yaml_catalogs = load_combo_catalog()
  File "/home/dylan/work/xicam/intake/intake/catalog/default.py", line 99, in load_combo_catalog
    return YAMLFilesCatalog(cat_dirs, name='builtin', description=desc)
  File "/home/dylan/work/xicam/intake/intake/catalog/local.py", line 710, in __init__
    super(YAMLFilesCatalog, self).__init__(**kwargs)
  File "/home/dylan/work/xicam/intake/intake/catalog/base.py", line 113, in __init__
    self.force_reload()
  File "/home/dylan/work/xicam/intake/intake/catalog/base.py", line 170, in force_reload
    self._load()
  File "/home/dylan/work/xicam/intake/intake/catalog/local.py", line 760, in _load
    raise ValueError(
ValueError: Conflicting names when flattening multiple catalogs. Sources {'intake_server'} exist in more than one
QProcess: Destroyed while process ("/home/dylan/work/xicam/env/bin/python") is still running.

**Comment by ronpandolfi** [comment]
Has this been addressed or raised with the intake folks? This is really an intake problem.

**Comment by dylanmcreynolds** [comment]
Is it? It seems to me that they're throwing an error when an error should be thrown (mis-configuration of intake files). Shouldn't xicam be able to catch that? Or do you think that intake should not be throwing errors?

**Comment by dylanmcreynolds** [comment]
FWIW, I am seeing this in Splash...I believe it's an issue with intake and threading. Will research and report back.

**Comment by dylanmcreynolds** [comment]
I have reported this issue to intake:  https://github.com/intake/intake/issues/556#issuecomment-743219283  

FWIW, in splash I have worked around the issue by caching the top level catalogs. Something like:


from databroker import catalog

```
cache = {}
def get_top_cat(cat_name: str):
  if not cache.get(cat_name):
    cache[cat_name] = catalog[cat_name]
  return cache[cat_name]
```

Not only does this avoid the error, but I found that on a local system with only two sources, the call to get the top level sources from a yaml catalog was taking about 500ms each time.
